# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MosaicPreview
                                 A QGIS plugin
 Preview drone images in QGIS using GPS metadata. Supports footprint, georeferenced images, and mosaic preview.
—
Vista previa de imágenes de dron en QGIS usando metadatos GPS. Soporta footprints, imágenes georreferenciadas y mosaico rápido.

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-19
        copyright            : (C) 2025 by Techno Analytics
        email                : info@bitechnoanalytics.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MosaicPreview class from file MosaicPreview.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mosaic_preview import MosaicPreview
    return MosaicPreview(iface)
