
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mosaic_preview_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MosaicPreviewDialogBase(object):
    def setupUi(self, MosaicPreviewDialogBase):
        MosaicPreviewDialogBase.setObjectName("MosaicPreviewDialogBase")
        MosaicPreviewDialogBase.resize(338, 341)
        self.verticalLayout = QtWidgets.QVBoxLayout(MosaicPreviewDialogBase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.folderLayout = QtWidgets.QHBoxLayout()
        self.folderLayout.setObjectName("folderLayout")
        self.folderLineEdit = QtWidgets.QLineEdit(MosaicPreviewDialogBase)
        self.folderLineEdit.setObjectName("folderLineEdit")
        self.folderLayout.addWidget(self.folderLineEdit)
        self.selectFolderButton = QtWidgets.QPushButton(MosaicPreviewDialogBase)
        self.selectFolderButton.setObjectName("selectFolderButton")
        self.folderLayout.addWidget(self.selectFolderButton)
        self.verticalLayout.addLayout(self.folderLayout)
        self.folderStatusLabel = QtWidgets.QLabel(MosaicPreviewDialogBase)
        self.folderStatusLabel.setObjectName("folderStatusLabel")
        self.verticalLayout.addWidget(self.folderStatusLabel)
        self.checkboxLayout = QtWidgets.QHBoxLayout()
        self.checkboxLayout.setObjectName("checkboxLayout")
        self.footprintCheckbox = QtWidgets.QCheckBox(MosaicPreviewDialogBase)
        self.footprintCheckbox.setObjectName("footprintCheckbox")
        self.checkboxLayout.addWidget(self.footprintCheckbox)
        self.geoimageCheckbox = QtWidgets.QCheckBox(MosaicPreviewDialogBase)
        self.geoimageCheckbox.setObjectName("geoimageCheckbox")
        self.checkboxLayout.addWidget(self.geoimageCheckbox)
        self.mosaicCheckbox = QtWidgets.QCheckBox(MosaicPreviewDialogBase)
        self.mosaicCheckbox.setObjectName("mosaicCheckbox")
        self.checkboxLayout.addWidget(self.mosaicCheckbox)
        self.verticalLayout.addLayout(self.checkboxLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.runButton = QtWidgets.QPushButton(MosaicPreviewDialogBase)
        self.runButton.setObjectName("runButton")
        self.buttonLayout.addWidget(self.runButton)
        self.clearButton = QtWidgets.QPushButton(MosaicPreviewDialogBase)
        self.clearButton.setObjectName("clearButton")
        self.buttonLayout.addWidget(self.clearButton)
        self.verticalLayout.addLayout(self.buttonLayout)
        self.outputTextEdit = QtWidgets.QTextEdit(MosaicPreviewDialogBase)
        self.outputTextEdit.setObjectName("outputTextEdit")
        self.verticalLayout.addWidget(self.outputTextEdit)

        self.retranslateUi(MosaicPreviewDialogBase)
        QtCore.QMetaObject.connectSlotsByName(MosaicPreviewDialogBase)

    def retranslateUi(self, MosaicPreviewDialogBase):
        _translate = QtCore.QCoreApplication.translate
        MosaicPreviewDialogBase.setWindowTitle(_translate("MosaicPreviewDialogBase", "Mosaic Preview"))
        self.selectFolderButton.setText(_translate("MosaicPreviewDialogBase", "Select Folder"))
        self.folderStatusLabel.setText(_translate("MosaicPreviewDialogBase", "No folder selected."))
        self.footprintCheckbox.setText(_translate("MosaicPreviewDialogBase", "Footprint"))
        self.geoimageCheckbox.setText(_translate("MosaicPreviewDialogBase", "GeoImage"))
        self.mosaicCheckbox.setText(_translate("MosaicPreviewDialogBase", "Mosaic"))
        self.runButton.setText(_translate("MosaicPreviewDialogBase", "Run"))
        self.clearButton.setText(_translate("MosaicPreviewDialogBase", "Clear"))
